---
# tasks file for roles/proxy
- name: Set front
  docker_container:
    state: started
    pull: true
    networks: 
      - name: app-network
    name: front
    image: abellech/tp-devops-image_front
    env:
      FRONTEND_host: api
    ports:
            - "82:80"
  vars:
      ansible_python_interpreter: /usr/bin/python3  


