---
# tasks file for roles/database

- name: Run database
  docker_container:
    state: started
    pull: true
    networks: 
      - name: app-network
    name: database
    image: abellech/tp-devops-image_database
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
  vars:
      ansible_python_interpreter: /usr/bin/python3  
