name: CI devops 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # Set up JDK 17 using actions/setup-java@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build and test with Maven
      - name: Build and test with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=tpdev-main-yml_analyse-main -Dsonar.organization=tpdev-main-yml -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file TP1_devops/API/simple-api-student-main/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    if: github.ref == 'refs/heads/main' && needs.test-backend.result == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.Docker_username}} -p ${{ secrets.Docker_token }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/API/simple-api-student-main
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_httpd:latest

  run-ansible-playbook:
    needs: build-and-push-docker-image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        run: ansible-playbook -i TP1_devops/ansible/inventories/setup.yml TP1_devops/ansible/playbook.yml        
