name: build-and-push-docker-image

on:
  workflow_run:
    workflows: ["test-backend"]
    types:
      - completed
    push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Verify Dockerfile paths
        run: |
          ls -la TP1_devops/API/simple-api-student-main
          ls -la TP1_devops/database
          ls -la TP1_devops/server
          ls -la TP1_devops/devops-front-main

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/API/simple-api-student-main
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push front
        uses: docker/build-push-action@v3
        with:
          context: TP1_devops/devops-front-main
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-image_front:latest
          push: ${{ github.ref == 'refs/heads/main' }}
