name: CD devops 2024
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        run: echo "${{ secrets.Docker_password }}" | docker login -u "${{ secrets.Docker_username }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest .
          docker push your-dockerhub-username/your-image-name:latest
