name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify --file TP1_devops/API/simple-api-student-main/pom.xml

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: TP1_devops/API/simple-api-student-main
          # Note: tags has to be all lower-case
          tags:  ${{secrets.Docker_username}}/tp-devops-image_api:latest
          # push: ${{ github.ref == 'refs/heads/main' }}



      - name: Build image and push database
       # DO the same for database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: TP1_devops/database
          # Note: tags has to be all lower-case
          tags:  ${{secrets.Docker_username}}/tp-devops-image_database:latest
          # push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
     # DO the same for httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: TP1_devops/server
          # Note: tags has to be all lower-case
          tags:  ${{secrets.Docker_username}}/tp-devops-image_httpd:latest
          # push: ${{ github.ref == 'refs/heads/main' }}
  

